//+------------------------------------------------------------------+
//| {EA_NAME}.mq5                                                     |
//| Auto-generated by the Research pipeline — DO NOT EDIT BY HAND.    |
//| Instrument researched : {SYMBOL} ({PROVIDER}, {TIMEFRAME})        |
//| Generated             : {GENERATED_AT}                            |
//| Walk-forward AUC      : full model {FULL_AUC} / distilled {DIST_AUC} |
//| Backtest (OOS, net)   : {BT_SUMMARY}                              |
//|                                                                   |
//| The EA scores each new bar with a logistic model distilled from   |
//| the pipeline's LightGBM walk-forward model, using 12 portable     |
//| features computed identically to the research code. It opens a    |
//| CALL (buy) when P >= CallThreshold, a PUT (sell) when             |
//| P <= PutThreshold, with ATR-based SL and TP = RR * SL.            |
//| Research code: see the Research repo (pipeline/).                 |
//+------------------------------------------------------------------+
#property copyright "Research pipeline"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

input double RiskPercent   = {RISK_PCT};    // % of balance risked per trade
input double CallThreshold = {CALL_TH};     // P(win) needed to go long
input double PutThreshold  = {PUT_TH};      // P(win) below which to go short
input double SlAtrMult     = {SL_ATR};      // stop distance in ATR
input double RrRatio       = {RR};          // take-profit : stop-loss
input int    HorizonBars   = {HORIZON};     // time exit after N bars
input long   MagicNumber   = {MAGIC};

#define NFEAT 12
#define WARMUP 400

// distilled logistic model: z = b0 + sum(coef[i] * (x[i]-mean[i])/std[i])
double COEF[NFEAT] = { {COEFS} };
double MEAN[NFEAT] = { {MEANS} };
double STDV[NFEAT] = { {STDS} };
double INTERCEPT = {INTERCEPT};

CTrade trade;
datetime g_lastBar = 0;
datetime g_entryBar = 0;

//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(MagicNumber);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| EMA over close-index j (0 = oldest) with pandas ewm(adjust=false) |
//| recursion, seeded at the first value.                             |
//+------------------------------------------------------------------+
void EmaSeries(const double &src[], int n, double span, double &dst[])
  {
   double alpha = 2.0 / (span + 1.0);
   ArrayResize(dst, n);
   dst[0] = src[0];
   for(int i = 1; i < n; i++)
      dst[i] = alpha * src[i] + (1.0 - alpha) * dst[i - 1];
  }

void EwmAlpha(const double &src[], int n, double alpha, double &dst[])
  {
   ArrayResize(dst, n);
   dst[0] = src[0];
   for(int i = 1; i < n; i++)
      dst[i] = alpha * src[i] + (1.0 - alpha) * dst[i - 1];
  }

//+------------------------------------------------------------------+
//| Compute the 12 portable features on the last closed bar.          |
//| rates[] is chronological (oldest -> newest), newest = last CLOSED |
//| bar. Returns false during warmup.                                 |
//+------------------------------------------------------------------+
bool ComputeFeatures(double &x[])
  {
   MqlRates rates[];
   int n = CopyRates(_Symbol, _Period, 1, WARMUP, rates); // from last closed bar back
   if(n < WARMUP) return(false);
   ArraySetAsSeries(rates, false); // chronological

   double close[], open_[], high[], low[], tr[];
   ArrayResize(close, n); ArrayResize(open_, n);
   ArrayResize(high, n);  ArrayResize(low, n); ArrayResize(tr, n);
   for(int i = 0; i < n; i++)
     {
      close[i] = rates[i].close; open_[i] = rates[i].open;
      high[i] = rates[i].high;   low[i]  = rates[i].low;
      double hl = high[i] - low[i];
      if(i > 0)
        {
         double hc = MathAbs(high[i] - close[i - 1]);
         double lc = MathAbs(low[i] - close[i - 1]);
         tr[i] = MathMax(hl, MathMax(hc, lc));
        }
      else tr[i] = hl;
     }

   double e20[], e50[], e200[], a14[], m12[], m26[];
   EmaSeries(close, n, 20, e20);
   EmaSeries(close, n, 50, e50);
   EmaSeries(close, n, 200, e200);
   EwmAlpha(tr, n, 1.0 / 14.0, a14);
   EmaSeries(close, n, 12, m12);
   EmaSeries(close, n, 26, m26);

   double macd[]; ArrayResize(macd, n);
   for(int i = 0; i < n; i++) macd[i] = m12[i] - m26[i];
   double msig[];
   EmaSeries(macd, n, 9, msig);

   // Wilder RSI via ewm(alpha=1/14) on up/down moves
   double up[], dn[];
   ArrayResize(up, n); ArrayResize(dn, n);
   up[0] = 0; dn[0] = 0;
   for(int i = 1; i < n; i++)
     {
      double d = close[i] - close[i - 1];
      up[i] = (d > 0 ? d : 0);
      dn[i] = (d < 0 ? -d : 0);
     }
   double eup[], edn[];
   EwmAlpha(up, n, 1.0 / 14.0, eup);
   EwmAlpha(dn, n, 1.0 / 14.0, edn);

   int t = n - 1;                    // last closed bar
   double atr = a14[t];
   if(atr <= 0) return(false);

   double rsi_t  = (edn[t] > 0 ? 100.0 - 100.0 / (1.0 + eup[t] / edn[t]) : 100.0);
   int t5 = t - 5;
   double rsi_t5 = (edn[t5] > 0 ? 100.0 - 100.0 / (1.0 + eup[t5] / edn[t5]) : 100.0);

   // SMA20 + population std, Donchian 20, ATR SMA50
   double sma20 = 0, var20 = 0, atrsma = 0;
   double dchi = high[t], dclo = low[t];
   for(int i = 0; i < 20; i++)
     {
      sma20 += close[t - i];
      if(high[t - i] > dchi) dchi = high[t - i];
      if(low[t - i]  < dclo) dclo = low[t - i];
     }
   sma20 /= 20.0;
   for(int i = 0; i < 20; i++) var20 += MathPow(close[t - i] - sma20, 2);
   var20 /= 20.0;
   for(int i = 0; i < 50; i++) atrsma += a14[t - i];
   atrsma /= 50.0;

   double sgn1 = (e20[t] > e50[t] ? 1 : (e20[t] < e50[t] ? -1 : 0));
   double sgn2 = (e50[t] > e200[t] ? 1 : (e50[t] < e200[t] ? -1 : 0));
   double rng  = high[t] - low[t];

   x[0]  = sgn1 + sgn2;                                   // p_ema_align
   x[1]  = (e50[t] - e50[t - 10]) / atr;                  // p_ema50_slope
   x[2]  = (close[t] - e50[t]) / atr;                     // p_dist_e50
   x[3]  = (close[t] - e200[t]) / atr;                    // p_dist_e200
   x[4]  = rsi_t;                                         // p_rsi
   x[5]  = rsi_t - rsi_t5;                                // p_rsi_slope
   x[6]  = (macd[t] - msig[t]) / close[t] * 10000.0;      // p_macd_hist
   x[7]  = (atrsma > 0 ? atr / atrsma : 1.0);             // p_atr_ratio
   x[8]  = 4.0 * MathSqrt(var20) / sma20 * 100.0;         // p_bb_width
   x[9]  = (dchi > dclo ? (close[t] - dclo) / (dchi - dclo) : 0.5); // p_donch_pos
   x[10] = (close[t] - close[t5]) / atr;                  // p_ret5_atr
   x[11] = (rng > 0 ? (close[t] - open_[t]) / rng : 0);   // p_body
   for(int i = 0; i < NFEAT; i++)
     {
      if(x[i] > 50) x[i] = 50;
      if(x[i] < -50) x[i] = -50;
     }
   return(true);
  }

//+------------------------------------------------------------------+
double Score(const double &x[])
  {
   double z = INTERCEPT;
   for(int i = 0; i < NFEAT; i++)
      if(STDV[i] > 0) z += COEF[i] * (x[i] - MEAN[i]) / STDV[i];
   return(1.0 / (1.0 + MathExp(-z)));
  }

//+------------------------------------------------------------------+
double LotsForRisk(double slDistance)
  {
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0 || slDistance <= 0) return(0.0);
   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * RiskPercent / 100.0;
   double lossPerLot = slDistance / tickSize * tickValue;
   double lots = riskMoney / lossPerLot;
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double stepLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots / stepLot) * stepLot;
   return(MathMin(maxLot, MathMax(minLot, lots)));
  }

//+------------------------------------------------------------------+
bool HasOpenPosition()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)
         && PositionGetString(POSITION_SYMBOL) == _Symbol
         && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
         return(true);
     }
   return(false);
  }

void CloseExpiredPosition()
  {
   if(!HasOpenPosition()) return;
   int barsHeld = Bars(_Symbol, _Period, g_entryBar, TimeCurrent()) - 1;
   if(barsHeld >= HorizonBars)
      trade.PositionClose(_Symbol);
  }

//+------------------------------------------------------------------+
void OnTick()
  {
   datetime barTime = iTime(_Symbol, _Period, 0);
   if(barTime == g_lastBar) { CloseExpiredPosition(); return; }
   g_lastBar = barTime;   // a new bar just opened -> bar 1 is freshly closed

   CloseExpiredPosition();
   if(HasOpenPosition()) return;

   double x[NFEAT];
   if(!ComputeFeatures(x)) return;
   double p = Score(x);

   MqlRates r[];
   if(CopyRates(_Symbol, _Period, 1, 15, r) < 15) return;
   ArraySetAsSeries(r, false);
   // quick ATR for order geometry (same recursion, short warmup is fine here
   // because ComputeFeatures already gated on full warmup)
   double atr = 0;
   for(int i = 1; i < 15; i++)
     {
      double tr = MathMax(r[i].high - r[i].low,
                  MathMax(MathAbs(r[i].high - r[i - 1].close),
                          MathAbs(r[i].low - r[i - 1].close)));
      atr = (i == 1 ? tr : (tr / 14.0 + atr * 13.0 / 14.0));
     }
   if(atr <= 0) return;

   double slDist = SlAtrMult * atr;
   double tpDist = RrRatio * slDist;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double lots;

   if(p >= CallThreshold)
     {
      lots = LotsForRisk(slDist);
      if(lots > 0 && trade.Buy(lots, _Symbol, ask, ask - slDist, ask + tpDist,
                               "pipeline CALL p=" + DoubleToString(p, 3)))
         g_entryBar = barTime;
     }
   else if(p <= PutThreshold)
     {
      lots = LotsForRisk(slDist);
      if(lots > 0 && trade.Sell(lots, _Symbol, bid, bid + slDist, bid - tpDist,
                                "pipeline PUT p=" + DoubleToString(p, 3)))
         g_entryBar = barTime;
     }
  }
//+------------------------------------------------------------------+
